- bucket: !!binary |
    Z0FBQUFBQmFaSmV4ZVF1aDJnV0o3Qm83ajlSa3VUelRNM2F3a3laZEEzWlRveVliRUQyZlp4X016
    ODF3MS1HdlBTUHZUeHJ4SzVaSVR0TTRGaDdLdEFQWVZPYkR5Rzd0UVdVMW5KSHY2UzFNY2J0eW9r
    YnlDSGs9
  created_at: '2018-01-03T10:55:42.854Z'
  email: 27b6f3ebc1535b4b11b1508ec7c7364c
  id: 5a4cb6ae8df9df36f12c16c5
  message: من یه دامنه و هاست دارم که به هم متصل بودن، تصورم این بود که میشه مثل CloudFlare
    این Netlify رو بین این دو قرار بدم، وارد Netlify شدم و دامنم رو به DNS Zone اضافه
    کردم، چهار تا NameServer داد که دامنم روی اونا تنظیم کردم، بعد تو Netlify اومدم
    توی قسمت DNS Records دو تا NameServer هاستم رو در قالب  NS وارد کردم، الان بعد
    یه روز دامنم به هاست متصل نمیشه. نمیدونم ایراد کارم کجاست؟
  name: روح اله
  page_id: /netlify
  reply_to: null
  website: ''
- bucket: !!binary |
    Z0FBQUFBQmFaSmV4S3hsd1ctRDh3NWp4OWVQTkd3VjZuajlYQ1l5MHNBd3FGUWhrMFJrRDNnMWVH
    VFJtcXN6YXdmQmdPZktiWlluUE1zd0dzbU51R1Q4MUFsb3k2UzU3MFE5UzNzd29fSURBLVMzaHlL
    cXlRLU09
  created_at: '2018-01-03T15:39:47.386Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  id: 5a4cf9438df9df223b2c16c9
  message: "> تصورم این بود که میشه مثل CloudFlare این Netlify رو بین این دو قرار\
    \ بدم\r\n\r\nنتلیفای سایت دیگه‌ای رو نمی‌تونه سرو کنه. همه چیز باید رو خودش باشه.\
    \ مناسب سایتهای استاتیکه.\r\n\r\n> بعد تو Netlify اومدم توی قسمت DNS Records دو\
    \ تا NameServer هاستم رو در قالب NS وارد کردم\r\n\r\nاین قسمت فقط به درد تعریف\
    \ رکوردهای جدید می‌خوره. مثلا تعریف زیر دامنه برای ایمیل. نمی‌تونی هاستت خودت\
    \ رو اینجا وارد کنی.\r\n\r\nکلا نمی‌تونی از نتلیفای برای اضافه کردن https به سرور\
    \ یا هاست شخصی خودت استفاده کنی مگر اینکه استاتیک باشه و کاملا از روی نتلیفای\
    \ سرو بشه. مطلب رو اصلاح می‌کنم که باعث سردرگمی نشه."
  name: مهدی صادقی
  page_id: /netlify
  reply_to: null
  website: https://mehdix.ir
